# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
