# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170718_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=models.TextField(),
        ),
    ]
